### ISSUE TITLE
Uploads not working

### ISSUE THREAD

**Issue by bergie** [chbrown/flickr-with-uploads#2]
I managed to get the necessary tokens generated, and can verify that they work by fetching info on a private image.

However, uploading doesn't work. I get:

```
oauth_problem=parameter_absent&oauth_parameters_absent=oauth_signature
SyntaxError: Unexpected token o
```

**Comment by chbrown** [comment]
Make sure your "params" argument to the FlickrRequest constructor is a javascript object, not a string. Thus: {oauth_problem: "parameter_absent", oauth_parameters_absent: "oauth_signature"} instead of "oauth_problem=parameter_absent&oauth_parameters_absent=oauth_signature".

**Comment by bergie** [comment]
@chbrown the params appear to be correctly a JS object, so that isn't the problem. If I do a `console.log(form);` in  `FlickrRequest.prototype.sendPOST`, I see each parameter, including `oauth_signature` in the form's `_streams`.

The `oauth_problem=parameter_absent&oauth_parameters_absent=oauth_signature` string is what gets sent to `FlickrRequest.prototype.processResponse`

**Comment by chbrown** [comment]
I'm not sure how to recreate locally, so I won't try to fix right now, but: 1) you can add an attempt to querystring parse at lib/flickr.js:101, and/or 2) let me know what command you're trying to execute (an upload?), and the full response_body that gets console.error'd in :110.

**Comment by bergie** [comment]
@chbrown I'm trying upload, the form looks OK (though I haven't seen one that worked so there might be something wrong), authentication works when reading.

`oauth_problem=parameter_absent&oauth_parameters_absent=oauth_signature` is the full response body.

Here is part of the code I'm running:

``` javascript
var client = new Flickr(apiKey, apiSecret, apiToken, apiTSecret);

var api = function(method, data, cb) {
  var req = client.createRequest(method, data, true, cb);
  return req.send();
};
```

This works:

``` javascript
api('flickr.photos.getInfo', {
  photo_id: '4992745376'
}, function(err, response) {});
```

This doesn't:

``` javascript
var location = __dirname + "/blobs/" + image.location;
var stream = fs.createReadStream(location, {
  flags: 'r'
});

var imgData = {
  title: image.title,
  tags: image.tags.join(' '),
  is_public: 1,
  photo: stream
};
api('upload', imgData, function(err, response) {
  return console.log(err.toString());
});
```

**Comment by chbrown** [comment]
Okay, I understand now that "oauth_problem=parameter_absent&oauth_parameters_absent=oauth_signature" is the error message you're getting back from Flickr. Can you verify that my node-oauth fork is installed, and not ciaranj's? I forked his to enable Flickr uploads, so it makes sense that you're getting an error if you're still using ciaranj's.

**Comment by chbrown** [comment]
BTW it's in my flickr-with-uploads package.json, as well as https://github.com/chbrown/node-oauth

**Comment by bergie** [comment]
@chbrown correct, I have your version of it. I think the issue is in the form submission. If I console log the form after `form.append('photo', this.params.photo);` in `form.append('photo', this.params.photo);`, it contains these keys:

``` json
{ _overheadLength: 1626,
  _valueLength: 210,
  _lengthRetrievers: [ [Function] ],
  writable: false,
  readable: true,
  dataSize: 0,
  maxDataSize: 2097152,
  pauseStreams: true,
  _released: false,
  _streams: 
   [ '----------------------------854940644850963409864704\r\nContent-Disposition: form-data; name="api_key"\r\n\r\n',
      <snip>
     [Function],
     '----------------------------854940644850963409864704\r\nContent-Disposition: form-data; name="format"\r\n\r\n',
     'json',
     [Function],
     '----------------------------854940644850963409864704\r\nContent-Disposition: form-data; name="is_public"\r\n\r\n',
     '1',
     [Function],
     '----------------------------854940644850963409864704\r\nContent-Disposition: form-data; name="nojsoncallback"\r\n\r\n',
     '1',
     [Function],
     '----------------------------854940644850963409864704\r\nContent-Disposition: form-data; name="oauth_consumer_key"\r\n\r\n',
      <snip>
     [Function],
     '----------------------------854940644850963409864704\r\nContent-Disposition: form-data; name="oauth_nonce"\r\n\r\n',
        <snip>
     [Function],
     '----------------------------854940644850963409864704\r\nContent-Disposition: form-data; name="oauth_signature_method"\r\n\r\n',
     'HMAC-SHA1',
     [Function],
     '----------------------------854940644850963409864704\r\nContent-Disposition: form-data; name="oauth_timestamp"\r\n\r\n',
     '1350565965',
     [Function],
     '----------------------------854940644850963409864704\r\nContent-Disposition: form-data; name="oauth_token"\r\n\r\n',
       <snip>
     [Function],
     '----------------------------854940644850963409864704\r\nContent-Disposition: form-data; name="oauth_version"\r\n\r\n',
     '1.0A',
     [Function],
     '----------------------------854940644850963409864704\r\nContent-Disposition: form-data; name="tags"\r\n\r\n',
     '',
     [Function],
     '----------------------------854940644850963409864704\r\nContent-Disposition: form-data; name="title"\r\n\r\n',
      <snip>
     [Function],
     '----------------------------854940644850963409864704\r\nContent-Disposition: form-data; name="oauth_signature"\r\n\r\n',
      <snip>
     [Function],
     '----------------------------854940644850963409864704\r\nContent-Disposition: form-data; name="photo"; filename="8d18298e2f293c7326d2f0c9841aa52b"\r\nContent-Type: application/octet-stream\r\n\r\n',
     { source: [Object],
       dataSize: 0,
       maxDataSize: Infinity,
       pauseStream: true,
       _maxDataSizeExceeded: false,
       _released: false,
       _bufferedEvents: [Object],
       _events: [Object] },
     [Function] ],
  _currentStream: null,
  _boundary: '--------------------------854940644850963409864704' }
```

(note: I've removed the actual values of the various keys and signatures.

**Comment by chbrown** [comment]
Can you also console.log "querystring_parts" before they get added to the form, the version of felixge's form-data that npm downloaded, and the version of node that you're running? I don't think those "[Function]"'s should be in the form output, do you?

**Comment by bergie** [comment]
@chbrown that is the form object with its streams, not the actual output. But anyway, here are my installed packages:

```
└─┬ flickr-with-uploads@0.2.2 
  ├─┬ form-data@0.0.4 
  │ ├── async@0.1.22 
  │ ├─┬ combined-stream@0.0.3 
  │ │ └── delayed-stream@0.0.5 
  │ └── mime@1.2.7 
  └── oauth@0.9.9 
```

**Comment by chbrown** [comment]
Can you try form-data@0.0.3? The node I last used this with was 0.8.11, btw.

**Comment by bergie** [comment]
Exactly the same issue with form-data 0.0.3

**Comment by chbrown** [comment]
Dunno then. Sorry! Let me know if you eventually get it to work.

**Comment by bergie** [comment]
@chbrown just to check: it works for you? Can you post the results you get from `npm list`?

**Comment by chbrown** [comment]
I've only used it from another app (flickr-backup, also on github), so here's the npm list for that:

``` sh
flickr-backup@0.0.3 /Users/chbrown/github/flickr-backup
├─┬ flickr-with-uploads@0.2.2
│ ├─┬ form-data@0.0.3
│ │ ├── async@0.1.9
│ │ ├─┬ combined-stream@0.0.3
│ │ │ └── delayed-stream@0.0.5
│ │ └── mime@1.2.2
│ └── oauth@0.9.8
├─┬ glob@3.1.12
│ ├── graceful-fs@1.1.10
│ ├── inherits@1.0.0
│ └─┬ minimatch@0.2.5
│   └── lru-cache@1.1.1
├─┬ optimist@0.3.4
│ └── wordwrap@0.0.2
└─┬ redis@0.7.2 extraneous
  └── hiredis@0.1.14
```

**Comment by bergie** [comment]
@chbrown got it! The problem was sending an empty list of tags. Fixed by:

``` javascript
if (image.tags) {
  imgData.tags = image.tags.join(' ');
}
```

**Comment by chbrown** [comment]
That is ridiculous. Fantastic error message on Flickr's part. Glad it works for you though.

**Comment by bergie** [comment]
@chbrown and thanks for the help!
