### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by nambrot** [chbrown/flickr-with-uploads#8]
So I started to use this great lib to sync my photos to flickr. The first error I received was this: 

```
 /usr/local/lib/node_modules/flickr-with-uploads/orm/photo.js:32
   return new Photo(obj.id, obj.title, obj.isprimary, obj.ispublic, obj.isfrien
```

I traced it down to 

```
  this.api({method: 'flickr.photos.search', user_id: this.id, tags: 'api'}, function(err, 
```

no returning any photos which in turn is caused because the user_id is 'me'

The story continues

**Comment by nambrot** [comment]
It seems like the Cruz is on this line:

https://github.com/chbrown/flickr-with-uploads/blob/master/bin/flickr-commands-sync.js#L26

I print out request which is just a function. I'm unfortunately not too well versed to know what that means however.

**Comment by chbrown** [comment]
Oh, right. Flickr requires a cover photo when you create a photoset (which is annoying and kind of backward in my opinion) and the way I get that here is by finding a special photo of mine that is tagged as "api". That's something I should fix, but for now you can manually upload some placeholder image (via Flickr website), add "api" to its tags, and it'll be found there.

**Comment by nambrot** [comment]
so theoretically, we could just upload the first picture of the set without a photoset and then use its id as a coverphoto?

**Comment by chbrown** [comment]
Yes; I expect that's what Flickr intends for people to do.

**Comment by nambrot** [comment]
Aight, I just followed your method so far by tagging one of my pictures with API. I might add a function to the library that goes through photosets and just sets the cover photo to the first picture automatically

**Comment by nambrot** [comment]
Works like a charm. And having 21MB/s is very satisfying :)
